# ========== Profile ========== #
# avatar
avatar: /avatar/Misaka.jpg
# author name
author: fi3ework
# signature
signature: witness me
# SNS
social:
  email: 805843200@qq.com
  github: //github.com/fi3ework
  weibo: //github.com/fi3ework
  zhihu: //github.com/fi3ework
  douban: //github.com/fi3ework
  facebook: //github.com/fi3ework
  twitter: //github.com/fi3ework
  instagram: //github.com/fi3ework
  stack-overflow: //github.com/fi3ework
  linkedin: //github.com/fi3ework
  others: //github.com/fi3ework
  rss: atom.xml
# friends
friends:
  Mason Zhou: https://github.com/Mason1993
  Wang Tao: https://github.com/wwtdsg
  # friendC :
# about
about:
  enable: true
  # image: '/intro/about-page.jpg'
  image: 'http://i4.bvimg.com/622343/902b16fb28923fe9s.png'

# ========== Site ========== #
# title of the site
SEO_title: fi3ework's Studio
# main title
main_title: fi3ework's Studio.
# subtitle
subtitle: it's better to burn out than to fade away
# site haeder image
site_header_image: 'http://oumn0o088.bkt.clouddn.com/intro-desktop.jpg'
# post haeder image
post_header_image: 'http://oumn0o088.bkt.clouddn.com/post-bg.jpg'
# 404 image
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== Comment ========== #
# 目前只支持一键添加livere评论（因为懒），其他评论插件可自行添加
comment:
  # change the value of livere to your livere data-uid
  livere_uid: MTAyMC8yODQyOS81MDAw
  # disqus
  # disqus_shortname: firework-studio
  # changyan
  #changyan_appid: cysYkbwD3
  #changyan_conf: prod_1272d58a007a19d9e03ad7cbec1f0ada
  # gitment
  # gitment_owner: fi3ework
  # gitment_repo: fi3ework.github.io
  # gitment_client_id: 173b36b0a164e0d952c9
  # gitment_client_secret: 615a76cab99505a9bc66269569475cf9447a3272
  # youyan 
  # youyan_uid: '2146978'


# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: true
# Baidu analytics
baidu_analytics: 'https://hm.baidu.com/hm.js?c2e692c5407f95609121a9d80bd24510'
# Google analytics
# google_analytics: 'UA-103985966-1'
# CNZZ analytics
# CNZZ_analytics: '1263255655'

# ========== Others ========== #
# favicon
favicon: /assets/favicon.ico
# truncate length (the default is 300)
truncate_length:
# enable toc
toc: true
